version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: "Europe/Warsaw"
  open-pull-requests-limit: 0
  rebase-strategy: "disabled"