#  Copyright 2022 OneWelcome B.V.
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.
version: 2.1

orbs:
  onegini-build: onegini/onegini-build@dev:832cea5e4205474e9225388cfdfe0c615089aa84

.dev-context-and-executor: &dev-context
  context: dev-context

.require-build: &require-build
  requires:
    - build

.require-test: &require-test
  requires:
    - test

.filter-master-only: &filter-master-only
  filters:
    branches:
      only: master

.filter-branches-tags: &filter-branches-tags
  filters:
    tags:
      only: /.*/

.filter-tags: &filter-tags
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

.filter-no-dependabot-and-no-master: &filter-no-dependabot-and-no-master
  filters:
    branches:
      ignore: /dependabot\/.*|master/

jobs:
  build-storybook:
    description: Build the Storybook of this project
    parameters:
      executor:
        description: The executor to use.
        type: executor
        default: onegini-build/node-executor
    executor: << parameters.executor >>
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Storybook build
          command: npm run build-storybook
      - persist_to_workspace:
          root: ~/
          paths:
            - project/storybook-static

  deploy-storybook-to-github-pages:
    executor: onegini-build/node-executor
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install gh-pages
          command: npm install --prefix=$HOME/.local -g --silent gh-pages
      - run:
          name: Add host
          command: |
            mkdir ~/.ssh
            touch ~/.ssh/known_hosts
            ssh-keyscan -H github.com > ~/.ssh/known_hosts
      - run:
          name: Run deploy
          command: gh-pages -d storybook-static -u "github-actions-bot <support+actions@github.com>"

  chromatic-deployment:
    executor: onegini-build/node-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}

workflows:
  version: 2
  build-workflow:
    jobs:
      - onegini-build/npm-build:
          name: build
          dependency_install_command: npm ci --ignore-script
          <<: *dev-context
          <<: *filter-branches-tags

      - onegini-build/npm-lint:
          name: lint
          <<: *dev-context
          <<: *require-build
          <<: *filter-branches-tags

      - onegini-build/npm-test-jest:
          name: test
          <<: *dev-context
          <<: *require-build
          <<: *filter-branches-tags

      - onegini-build/sonar:
          name: analyse
          <<: *dev-context
          <<: *require-test

      - approve-chromatic:
          name: approve-chromatic
          type: approval
          <<: *filter-no-dependabot-and-no-master
          requires:
            - build

      - chromatic-deployment:
          name: chromatic-deployment
          <<: *dev-context
          <<: *filter-no-dependabot-and-no-master
          <<: *filter-branches-tags
          requires:
            - approve-chromatic

      - build-storybook:
          name: build-storybook
          <<: *dev-context
          <<: *require-build
          <<: *filter-branches-tags

      - onegini-build/deploy-docs:
          name: deploy-storybook-release
          context: internal-docs
          s3_bucket: onegini-internal-docs-storage-production
          site_location: storybook-static/
          path_in_bucket: html/react-lib-components-release
          executor:
            name: onegini-build/docs-builder
          <<: *filter-tags
          requires:
            - test
            - build-storybook

      - onegini-build/deploy-docs:
          name: deploy-storybook-snapshot
          context: internal-docs
          s3_bucket: onegini-internal-docs-storage-production
          site_location: storybook-static/
          path_in_bucket: html/react-lib-components-snapshot
          executor:
            name: onegini-build/docs-builder
          <<: *filter-master-only
          requires:
            - test
            - build-storybook

      - onegini-build/npm-publish:
          name: publish-library
          <<: *dev-context
          <<: *require-test
          <<: *filter-tags

      - onegini-build/notify-released:
          name: notify-released
          <<: *dev-context
          <<: *filter-tags
          requires:
            - publish-library

      - deploy-storybook-to-github-pages:
          name: deploy-github-pages
          <<: *filter-tags
          requires:
            - build-storybook
